### ISSUE TITLE
트위터, 페이스북 로고가 뒤바뀜

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/skin#85]
<img width="418" alt="스크린샷 2019-05-08 오후 6 04 07" src="https://user-images.githubusercontent.com/4435445/57363263-b8841e00-71bb-11e9-8d53-2b442ef0b561.png">

바꿔주자

https://github.com/femiwiki/skin/commit/e5f69eb7 에서 잘못 추가된것이 원인으로 보임

**Comment by lens0021** [comment]
[미디어위키:Femiwiki.css](https://femiwiki.com/w/%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Femiwiki.css)도 수정함(https://femiwiki.com/index.php?diff=143401)
